name: GITHUB_OUTPUT
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: output
        id: source
        run: echo "result=Hello" >> "$GITHUB_OUTPUT"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "$RESULT"
