name: sercrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
      PASS: ${{ secrets.PASS }}
    steps:
      - run: echo "${ PASSWORD }"
      - run: echo "${ PASSWORD:0:1 } ${PASSWORD#?}"
      - run: echo "${ PASS }"
